changelog:
  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement
        - feature

    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix

    - title: "🧹 Maintenance"
      labels:
        - documentation
        - refactor
        - chore
        - cleanup

    - title: "🔄 Uncategorized Changes"
      labels: [] # catch all for any changes without labels
