name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
filter-by-commitish: true

template: |
  ## Versjonering

  Ta høyde for versjonerings standard. Vi følger [Semantic Versioning](https://semver.org/):
  - **Major** – Inkompatible API-endringer
  - **Minor** – Ny funksjonalitet som er bakoverkompatibel
  - **Patch** – Bakoverkompatible feilrettinger

  ## Endringer

  $CHANGES

  Velg hva som passer.
  
  ## 🚀 Ny funksjonalitet
  -

  ## 💥 Brytende endringer
  -

  ## 📦 Avhengighetsoppdateringer
  -
