package no.nav.pensjon.regler.domain.enum

enum class InngangUnntakEnum {
    FLYKT_ALDER,
    FLYKT_UFOREP,
    FLYKT_BARNEP,
    FLYKT_GJENLEV,
    DOD26_BARNEP,
    DOD26_GJENLEV,
    UFOR25_UFOREP,
    YRKESSKADE_BARNEP,
    YRKESSKADE_GJENLEV,
    YRKESSKADE_UFOREP,
    MINDRE5AR_BARNEP,
    MINDRE5AR_GJENLEV,
    MINDRE5AR_UFOREP,
    DOD26_ALDER,
    UFOR25_ALDER,
    YRKESSKADE_ALDER,
    HALV_MINPEN_UFOREP,
    HALV_MINPEN_BARNEP,
    HALV_MINPEN_GJENLEV,
    HALV_MINPEN_ALDER,
    DOD26_UFOREP,
    HALV_MINPEN_UFP_UT;
}