package no.nav.pensjon.regler.domain.enum

enum class ResultattypeEnum {
    AP_GJP,
    AP_GJP_UP,
    AP_GJP_UP_YP,
    GJP_UP_YP,
    UP_GJP,
    UP_GJP_UP,
    UP_GJP_UP_YP,
    UP_YP,
    UT_YT,
    YT,
    YP,
    FORELOPIG_UP,
    BP1,
    BP2,
    FAMP,
    GJP_UP,
    GJP_MOR,
    GJP_FAR,
    TENKT_GJP,
    BP_FELLES,
    BP_SARKULL,
    TRYGDEAVTALE,
    TENKT_UTEN_INST,
    OMREGN_V_INST,
    AP2011,
    AP2011_GJP,
    AP2011_GJP_UP,
    AP2011_GJP_UP_YP,
    KONV_ALDER,
    KONV_AFP,
    AP2016,
    AP2025;
}