name: Manual Release (Github Package Registry)

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Maven release
        run: ./releaseGithub.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
