name: Manual Release (Github Package Registry)

on: workflow_dispatch

jobs:
  release:
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Run Maven release
        run: ./releaseGithub.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
