#name: Release (Github Package Registry)
#
#on:
#  push:
#    branches:
#    - 'master'
#
#jobs:
#  release:
#    permissions:
#      actions: read
#      checks: read
#      contents: read
#      deployments: write
#      packages: write
#      pull-requests: write
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Run Maven release
#        run: ./releaseGithub.sh
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
