name: Fetch All Release Notes

on: workflow_dispatch

jobs:
  fetch_release_notes:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Get all release notes
        id: fetch_release_notes
        run: |
          RELEASES=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases")
          RELEASE_NOTES=$(echo "$RELEASES" | jq -r '.[].body' | sed 's/^/* /')
          TAG_NAME=$(echo "$RELEASES" | jq -r '.[0].tag_name')
          echo "::set-output name=release_notes::$RELEASE_NOTES"
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: Output release notes
        run: |
          echo "All Release Notes:"
          echo "${{ steps.fetch_release_notes.outputs.release_notes }}"

      - name: Notify Slack about all releases
        run: |
          SLACK_MESSAGE="*Release Notes for Tag: ${{ steps.fetch_release_notes.outputs.tag_name }}*\n${{ steps.fetch_release_notes.outputs.release_notes }}"
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text": "'"$SLACK_MESSAGE"'"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}