name: Fetch All Release Notes

on: workflow_dispatch

jobs:
  fetch_release_notes:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Get all release notes
        id: fetch_release_notes
        run: |
          RELEASES=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases")
          RELEASE_NOTES=$(echo "$RELEASES" | jq -r '.[].body' | sed 's/^/* /')
          TAG_NAME=$(echo "$RELEASES" | jq -r '.[0].tag_name')
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Output release notes
        run: |
          echo "All Release Notes:"
          echo "${{ env.RELEASE_NOTES }}"

      - name: Notify Slack about all releases
        run: |
          SLACK_MESSAGE="*New release: ${{ env.TAG_NAME }}*\n${{ env.RELEASE_NOTES }}"
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text": "'"$SLACK_MESSAGE"'"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}