name: Fetch Latest Release Notes

on: workflow_dispatch

jobs:
  fetch_release_notes:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release notes
        id: fetch_release_notes
        run: |
          # Fetch the latest release information
          RELEASE=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")

          # Extract release notes and tag name
          RELEASE_NOTES=$(echo "$RELEASE" | jq -r '.body')
          TAG_NAME=$(echo "$RELEASE" | jq -r '.tag_name')

          # Escape newlines and special characters for GitHub environment
          SAFE_RELEASE_NOTES=$(echo "$RELEASE_NOTES" | sed ':a;N;$!ba;s/\n/\\n/g' | jq -R .)
          echo "RELEASE_NOTES=$SAFE_RELEASE_NOTES" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Format Slack release notes
        id: format_release_notes
        run: |
          # Replace escaped newlines with actual newlines
          RELEASE_NOTES=$(echo "${{ env.RELEASE_NOTES }}" | sed 's/\\n/\n/g' | sed 's/\\r//g')

          # Format the release notes for Slack
          FORMATTED_NOTES=$(echo "$RELEASE_NOTES" \
            | sed 's/^\* /• /g' \
            | sed 's/^  \* /  - /g')

          # Escape for safe GitHub environment variable usage
          echo "FORMATTED_NOTES<<EOF" >> $GITHUB_ENV
          echo "$FORMATTED_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify Slack about latest release
        run: |
          # Prepare Slack message
          SLACK_MESSAGE="*New release: ${{ env.TAG_NAME }}*\n${{ env.FORMATTED_NOTES }}"

          # Escape the entire Slack message for JSON payload
          ESCAPED_MESSAGE=$(echo "$SLACK_MESSAGE" | jq -R .)

          # Send the message to Slack
          PAYLOAD=$(jq -n --arg text "$ESCAPED_MESSAGE" '{"text": $text}')
          curl -X POST -H 'Content-type: application/json' \
            --data "$PAYLOAD" \
            ${{ secrets.SLACK_WEBHOOK_URL }}