name: Fetch Latest Release Notes

on: workflow_dispatch

jobs:
  fetch_release_notes:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release notes
        id: fetch_release_notes
        run: |
          RELEASE=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          RELEASE_NOTES=$(echo "$RELEASE" | jq -r '.body')
          TAG_NAME=$(echo "$RELEASE" | jq -r '.tag_name')

          # Escape newlines for proper formatting in the environment variable
          ESCAPED_RELEASE_NOTES=$(echo "$RELEASE_NOTES" | sed 's/\n/\\n/g' | sed 's/"/\\"/g')  # Escape both newline and quotes

          # Save the release notes and tag name as environment variables
          echo "RELEASE_NOTES=$ESCAPED_RELEASE_NOTES" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Output release notes
        run: |
          echo "Latest Release Notes:"
          echo "${{ env.RELEASE_NOTES }}"

      - name: Notify Slack about latest release
        run: |
          # Prepare Slack message
          SLACK_MESSAGE="*New release: ${{ env.TAG_NAME }}*\n${{ env.RELEASE_NOTES }}"

          # Send the message to Slack
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text": "'"${SLACK_MESSAGE}"'"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
